version: 2
jobs:
  build:
    docker:
      # Docker image version
      - image: circleci/node:8.4.0

    steps:
      # Checkout the code.
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Install Elm dependencies
          command: npm run elm-make

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  test:
    docker:
      - image: circleci/node:8.4.0

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Test the code
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
